networks:
  net_link:
    name: url-shortener-network
    driver: bridge

services:
  web:
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
    image: url-shortener/web
    container_name: url-shortener-web
    networks:
      - net_link
    hostname: ${WEB_HOSTNAME:-url-shortener-web}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${WEB_PORT:-3000}
      - REACT_APP_API_HOST=${REACT_APP_API_HOST:-http://localhost:3300/api}
    ports:
      - ${WEB_HOST_PORT:-3030}:${WEB_PORT:-3000}
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s      # Check every 30 seconds
      timeout: 10s       # Timeout after 10 seconds
      start_period: 15s  # Initial delay
      start_interval: 5s # Quick checks during startup
      retries: 3         # Retry up to 3 times before marking as unhealthy
    volumes:
      - ./bin/entrypoint.sh:/docker-entrypoint/entrypoint.sh:ro
      - ./bin/healthcheck.sh:/usr/local/bin/healthcheck.sh:ro
      - ./src:/app/src
      - ./public:/app/public
      - frontend_build:/app/build
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

volumes:
  frontend_build: